//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuX.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuX.Core.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ATPCCD 的本地化字符串。
        /// </summary>
        internal static string ATPCCD {
            get {
                return ResourceManager.GetString("ATPCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bool类型 的本地化字符串。
        /// </summary>
        internal static string bool类型 {
            get {
                return ResourceManager.GetString("bool类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Byte集合 的本地化字符串。
        /// </summary>
        internal static string Byte集合 {
            get {
                return ResourceManager.GetString("Byte集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 createInstanceErrorTips 的本地化字符串。
        /// </summary>
        internal static string createInstanceErrorTips {
            get {
                return ResourceManager.GetString("createInstanceErrorTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exceedMaxInstanceCountTips 的本地化字符串。
        /// </summary>
        internal static string exceedMaxInstanceCountTips {
            get {
                return ResourceManager.GetString("exceedMaxInstanceCountTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExistsAutoAllocatingParam_msg1 的本地化字符串。
        /// </summary>
        internal static string ExistsAutoAllocatingParam_msg1 {
            get {
                return ResourceManager.GetString("ExistsAutoAllocatingParam_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExistsAutoAllocatingParam_msg2 的本地化字符串。
        /// </summary>
        internal static string ExistsAutoAllocatingParam_msg2 {
            get {
                return ResourceManager.GetString("ExistsAutoAllocatingParam_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 int型 的本地化字符串。
        /// </summary>
        internal static string int型 {
            get {
                return ResourceManager.GetString("int型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Int数据集合 的本地化字符串。
        /// </summary>
        internal static string Int数据集合 {
            get {
                return ResourceManager.GetString("Int数据集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 int集合 的本地化字符串。
        /// </summary>
        internal static string int集合 {
            get {
                return ResourceManager.GetString("int集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入参类型 的本地化字符串。
        /// </summary>
        internal static string 入参类型 {
            get {
                return ResourceManager.GetString("入参类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入参长度 的本地化字符串。
        /// </summary>
        internal static string 入参长度 {
            get {
                return ResourceManager.GetString("入参长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭失败 的本地化字符串。
        /// </summary>
        internal static string 关闭失败 {
            get {
                return ResourceManager.GetString("关闭失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭超时 的本地化字符串。
        /// </summary>
        internal static string 关闭超时 {
            get {
                return ResourceManager.GetString("关闭超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出参类型 的本地化字符串。
        /// </summary>
        internal static string 出参类型 {
            get {
                return ResourceManager.GetString("出参类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string 创建时间 {
            get {
                return ResourceManager.GetString("创建时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始数据位 的本地化字符串。
        /// </summary>
        internal static string 原始数据位 {
            get {
                return ResourceManager.GetString("原始数据位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送数据失败 的本地化字符串。
        /// </summary>
        internal static string 发送数据失败 {
            get {
                return ResourceManager.GetString("发送数据失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送数据超时 的本地化字符串。
        /// </summary>
        internal static string 发送数据超时 {
            get {
                return ResourceManager.GetString("发送数据超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送等待结果失败 的本地化字符串。
        /// </summary>
        internal static string 发送等待结果失败 {
            get {
                return ResourceManager.GetString("发送等待结果失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 的本地化字符串。
        /// </summary>
        internal static string 在 {
            get {
                return ResourceManager.GetString("在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string 备注 {
            get {
                return ResourceManager.GetString("备注", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串 的本地化字符串。
        /// </summary>
        internal static string 字符串 {
            get {
                return ResourceManager.GetString("字符串", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在数据块发送失败 的本地化字符串。
        /// </summary>
        internal static string 存在数据块发送失败 {
            get {
                return ResourceManager.GetString("存在数据块发送失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实例无法创建 的本地化字符串。
        /// </summary>
        internal static string 实例无法创建 {
            get {
                return ResourceManager.GetString("实例无法创建", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        internal static string 已连接 {
            get {
                return ResourceManager.GetString("已连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string 异常 {
            get {
                return ResourceManager.GetString("异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string 成功 {
            get {
                return ResourceManager.GetString("成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行数据处理异常 的本地化字符串。
        /// </summary>
        internal static string 执行数据处理异常 {
            get {
                return ResourceManager.GetString("执行数据处理异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到指定语言 的本地化字符串。
        /// </summary>
        internal static string 找不到指定语言 {
            get {
                return ResourceManager.GetString("找不到指定语言", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到资源文件 的本地化字符串。
        /// </summary>
        internal static string 找不到资源文件 {
            get {
                return ResourceManager.GetString("找不到资源文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令名称 的本地化字符串。
        /// </summary>
        internal static string 指令名称 {
            get {
                return ResourceManager.GetString("指令名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令编号 的本地化字符串。
        /// </summary>
        internal static string 指令编号 {
            get {
                return ResourceManager.GetString("指令编号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收数据超时 的本地化字符串。
        /// </summary>
        internal static string 接收数据超时 {
            get {
                return ResourceManager.GetString("接收数据超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string 文件 {
            get {
                return ResourceManager.GetString("文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string 无 {
            get {
                return ResourceManager.GetString("无", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取自动分配标识的属性值所对应参数集合 的本地化字符串。
        /// </summary>
        internal static string 无法获取自动分配标识的属性值所对应参数集合 {
            get {
                return ResourceManager.GetString("无法获取自动分配标识的属性值所对应参数集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无须指定终端地址 的本地化字符串。
        /// </summary>
        internal static string 无须指定终端地址 {
            get {
                return ResourceManager.GetString("无须指定终端地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志参数设置成功 的本地化字符串。
        /// </summary>
        internal static string 日志参数设置成功 {
            get {
                return ResourceManager.GetString("日志参数设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无描述 的本地化字符串。
        /// </summary>
        internal static string 暂无描述 {
            get {
                return ResourceManager.GetString("暂无描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未接收到数据 的本地化字符串。
        /// </summary>
        internal static string 未接收到数据 {
            get {
                return ResourceManager.GetString("未接收到数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接 的本地化字符串。
        /// </summary>
        internal static string 未连接 {
            get {
                return ResourceManager.GetString("未连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浮点型 的本地化字符串。
        /// </summary>
        internal static string 浮点型 {
            get {
                return ResourceManager.GetString("浮点型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浮点数据集合 的本地化字符串。
        /// </summary>
        internal static string 浮点数据集合 {
            get {
                return ResourceManager.GetString("浮点数据集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浮点集合 的本地化字符串。
        /// </summary>
        internal static string 浮点集合 {
            get {
                return ResourceManager.GetString("浮点集合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机移动 的本地化字符串。
        /// </summary>
        internal static string 电机移动 {
            get {
                return ResourceManager.GetString("电机移动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控异常 的本地化字符串。
        /// </summary>
        internal static string 监控异常 {
            get {
                return ResourceManager.GetString("监控异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控数据 的本地化字符串。
        /// </summary>
        internal static string 监控数据 {
            get {
                return ResourceManager.GetString("监控数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控数据错误 的本地化字符串。
        /// </summary>
        internal static string 监控数据错误 {
            get {
                return ResourceManager.GetString("监控数据错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        internal static string 第 {
            get {
                return ResourceManager.GetString("第", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型错误 的本地化字符串。
        /// </summary>
        internal static string 类型错误 {
            get {
                return ResourceManager.GetString("类型错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码字符 的本地化字符串。
        /// </summary>
        internal static string 编码字符 {
            get {
                return ResourceManager.GetString("编码字符", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功 的本地化字符串。
        /// </summary>
        internal static string 获取成功 {
            get {
                return ResourceManager.GetString("获取成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        internal static string 行 {
            get {
                return ResourceManager.GetString("行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析异常 的本地化字符串。
        /// </summary>
        internal static string 解析异常 {
            get {
                return ResourceManager.GetString("解析异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名 的本地化字符串。
        /// </summary>
        internal static string 设备名 {
            get {
                return ResourceManager.GetString("设备名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置异常 的本地化字符串。
        /// </summary>
        internal static string 语言设置异常 {
            get {
                return ResourceManager.GetString("语言设置异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置成功 的本地化字符串。
        /// </summary>
        internal static string 语言设置成功 {
            get {
                return ResourceManager.GetString("语言设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言重复设置 的本地化字符串。
        /// </summary>
        internal static string 语言重复设置 {
            get {
                return ResourceManager.GetString("语言重复设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请指定终端地址 的本地化字符串。
        /// </summary>
        internal static string 请指定终端地址 {
            get {
                return ResourceManager.GetString("请指定终端地址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求成功 的本地化字符串。
        /// </summary>
        internal static string 请求成功 {
            get {
                return ResourceManager.GetString("请求成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时长 的本地化字符串。
        /// </summary>
        internal static string 超时时长 {
            get {
                return ResourceManager.GetString("超时时长", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接超时 的本地化字符串。
        /// </summary>
        internal static string 连接超时 {
            get {
                return ResourceManager.GetString("连接超时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重连失败 的本地化字符串。
        /// </summary>
        internal static string 重连失败 {
            get {
                return ResourceManager.GetString("重连失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重连异常 的本地化字符串。
        /// </summary>
        internal static string 重连异常 {
            get {
                return ResourceManager.GetString("重连异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重连成功 的本地化字符串。
        /// </summary>
        internal static string 重连成功 {
            get {
                return ResourceManager.GetString("重连成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 键名 的本地化字符串。
        /// </summary>
        internal static string 键名 {
            get {
                return ResourceManager.GetString("键名", resourceCulture);
            }
        }
    }
}
