//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.AutoTest.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.AutoTest.Language.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 采集模块 的本地化字符串。
        /// </summary>
        internal static string AcquireModule {
            get {
                return ResourceManager.GetString("AcquireModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATD2100Com 的本地化字符串。
        /// </summary>
        internal static string ATD2100Com {
            get {
                return ResourceManager.GetString("ATD2100Com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATD2100USB 的本地化字符串。
        /// </summary>
        internal static string ATD2100USB {
            get {
                return ResourceManager.GetString("ATD2100USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATD7100Com 的本地化字符串。
        /// </summary>
        internal static string ATD7100Com {
            get {
                return ResourceManager.GetString("ATD7100Com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATD7100USB 的本地化字符串。
        /// </summary>
        internal static string ATD7100USB {
            get {
                return ResourceManager.GetString("ATD7100USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EMCCD 的本地化字符串。
        /// </summary>
        internal static string EMCCD {
            get {
                return ResourceManager.GetString("EMCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M2电机 的本地化字符串。
        /// </summary>
        internal static string M2电机 {
            get {
                return ResourceManager.GetString("M2电机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围采集 的本地化字符串。
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围 的本地化字符串。
        /// </summary>
        internal static string Range1 {
            get {
                return ResourceManager.GetString("Range1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光谱 的本地化字符串。
        /// </summary>
        internal static string Spectrum {
            get {
                return ResourceManager.GetString("Spectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TC261 的本地化字符串。
        /// </summary>
        internal static string TC261 {
            get {
                return ResourceManager.GetString("TC261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TC261Area 的本地化字符串。
        /// </summary>
        internal static string TC261Area {
            get {
                return ResourceManager.GetString("TC261Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TEC制冷能力 的本地化字符串。
        /// </summary>
        internal static string TEC制冷能力 {
            get {
                return ResourceManager.GetString("TEC制冷能力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TEC温度监控 的本地化字符串。
        /// </summary>
        internal static string TEC温度监控 {
            get {
                return ResourceManager.GetString("TEC温度监控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toup2048 的本地化字符串。
        /// </summary>
        internal static string Toup2048 {
            get {
                return ResourceManager.GetString("Toup2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toup640 的本地化字符串。
        /// </summary>
        internal static string Toup640 {
            get {
                return ResourceManager.GetString("Toup640", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三阶信噪比 的本地化字符串。
        /// </summary>
        internal static string 三阶信噪比 {
            get {
                return ResourceManager.GetString("三阶信噪比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二阶信噪比 的本地化字符串。
        /// </summary>
        internal static string 二阶信噪比 {
            get {
                return ResourceManager.GetString("二阶信噪比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位移准确度 的本地化字符串。
        /// </summary>
        internal static string 位移准确度 {
            get {
                return ResourceManager.GetString("位移准确度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位移分辨力 的本地化字符串。
        /// </summary>
        internal static string 位移分辨力 {
            get {
                return ResourceManager.GetString("位移分辨力", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位移重复性 的本地化字符串。
        /// </summary>
        internal static string 位移重复性 {
            get {
                return ResourceManager.GetString("位移重复性", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好 的本地化字符串。
        /// </summary>
        internal static string 你好 {
            get {
                return ResourceManager.GetString("你好", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信噪比 的本地化字符串。
        /// </summary>
        internal static string 信噪比 {
            get {
                return ResourceManager.GetString("信噪比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光栅 的本地化字符串。
        /// </summary>
        internal static string 光栅 {
            get {
                return ResourceManager.GetString("光栅", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光谱分辨率 的本地化字符串。
        /// </summary>
        internal static string 光谱分辨率 {
            get {
                return ResourceManager.GetString("光谱分辨率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光谱列表 的本地化字符串。
        /// </summary>
        internal static string 光谱列表 {
            get {
                return ResourceManager.GetString("光谱列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光谱形状 的本地化字符串。
        /// </summary>
        internal static string 光谱形状 {
            get {
                return ResourceManager.GetString("光谱形状", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光谱范围 的本地化字符串。
        /// </summary>
        internal static string 光谱范围 {
            get {
                return ResourceManager.GetString("光谱范围", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全谱 的本地化字符串。
        /// </summary>
        internal static string 全谱 {
            get {
                return ResourceManager.GetString("全谱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反射光入光 的本地化字符串。
        /// </summary>
        internal static string 反射光入光 {
            get {
                return ResourceManager.GetString("反射光入光", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反射光出光 的本地化字符串。
        /// </summary>
        internal static string 反射光出光 {
            get {
                return ResourceManager.GetString("反射光出光", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可见光 的本地化字符串。
        /// </summary>
        internal static string 可见光 {
            get {
                return ResourceManager.GetString("可见光", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表 的本地化字符串。
        /// </summary>
        internal static string 图表 {
            get {
                return ResourceManager.GetString("图表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增益档位: 的本地化字符串。
        /// </summary>
        internal static string 增益档位 {
            get {
                return ResourceManager.GetString("增益档位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定标拟合 的本地化字符串。
        /// </summary>
        internal static string 定标拟合 {
            get {
                return ResourceManager.GetString("定标拟合", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定标调试 的本地化字符串。
        /// </summary>
        internal static string 定标调试 {
            get {
                return ResourceManager.GetString("定标调试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强度重复性 的本地化字符串。
        /// </summary>
        internal static string 强度重复性 {
            get {
                return ResourceManager.GetString("强度重复性", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UV8000超瞬态光谱仪 的本地化字符串。
        /// </summary>
        internal static string 拉曼自动测试软件 {
            get {
                return ResourceManager.GetString("拉曼自动测试软件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指令管理 的本地化字符串。
        /// </summary>
        internal static string 指令管理 {
            get {
                return ResourceManager.GetString("指令管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探测器型号 的本地化字符串。
        /// </summary>
        internal static string 探测器型号 {
            get {
                return ResourceManager.GetString("探测器型号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探测器类型 的本地化字符串。
        /// </summary>
        internal static string 探测器类型 {
            get {
                return ResourceManager.GetString("探测器类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  搜索 的本地化字符串。
        /// </summary>
        internal static string 搜索 {
            get {
                return ResourceManager.GetString("搜索", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string 操作 {
            get {
                return ResourceManager.GetString("操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string 无 {
            get {
                return ResourceManager.GetString("无", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示区test 的本地化字符串。
        /// </summary>
        internal static string 显示区 {
            get {
                return ResourceManager.GetString("显示区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暗噪声 的本地化字符串。
        /// </summary>
        internal static string 暗噪声 {
            get {
                return ResourceManager.GetString("暗噪声", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暗电流 的本地化字符串。
        /// </summary>
        internal static string 暗电流 {
            get {
                return ResourceManager.GetString("暗电流", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波长范围: 的本地化字符串。
        /// </summary>
        internal static string 波长范围 {
            get {
                return ResourceManager.GetString("波长范围", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试项 的本地化字符串。
        /// </summary>
        internal static string 测试项 {
            get {
                return ResourceManager.GetString("测试项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滤波权重: 的本地化字符串。
        /// </summary>
        internal static string 滤波权重 {
            get {
                return ResourceManager.GetString("滤波权重", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光 的本地化字符串。
        /// </summary>
        internal static string 激光 {
            get {
                return ResourceManager.GetString("激光", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灵敏度 的本地化字符串。
        /// </summary>
        internal static string 灵敏度 {
            get {
                return ResourceManager.GetString("灵敏度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点 的本地化字符串。
        /// </summary>
        internal static string 点 {
            get {
                return ResourceManager.GetString("点", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string 状态 {
            get {
                return ResourceManager.GetString("状态", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统配置 的本地化字符串。
        /// </summary>
        internal static string 系统配置 {
            get {
                return ResourceManager.GetString("系统配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线 的本地化字符串。
        /// </summary>
        internal static string 线 {
            get {
                return ResourceManager.GetString("线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        internal static string 结果 {
            get {
                return ResourceManager.GetString("结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脉冲补偿定标 的本地化字符串。
        /// </summary>
        internal static string 脉冲补偿定标 {
            get {
                return ResourceManager.GetString("脉冲补偿定标", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围 的本地化字符串。
        /// </summary>
        internal static string 范围 {
            get {
                return ResourceManager.GetString("范围", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        internal static string 设备 {
            get {
                return ResourceManager.GetString("设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备未连接 的本地化字符串。
        /// </summary>
        internal static string 设备未连接 {
            get {
                return ResourceManager.GetString("设备未连接", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        internal static string 设备管理 {
            get {
                return ResourceManager.GetString("设备管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言管理 的本地化字符串。
        /// </summary>
        internal static string 语言管理 {
            get {
                return ResourceManager.GetString("语言管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谱图名称 的本地化字符串。
        /// </summary>
        internal static string 谱图名称 {
            get {
                return ResourceManager.GetString("谱图名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置管理 的本地化字符串。
        /// </summary>
        internal static string 配置管理 {
            get {
                return ResourceManager.GetString("配置管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集 的本地化字符串。
        /// </summary>
        internal static string 采集 {
            get {
                return ResourceManager.GetString("采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集频率: 的本地化字符串。
        /// </summary>
        internal static string 采集频率 {
            get {
                return ResourceManager.GetString("采集频率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启软件 的本地化字符串。
        /// </summary>
        internal static string 重启软件 {
            get {
                return ResourceManager.GetString("重启软件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接设备 的本地化字符串。
        /// </summary>
        internal static string 链接设备 {
            get {
                return ResourceManager.GetString("链接设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长效稳定性 的本地化字符串。
        /// </summary>
        internal static string 长效稳定性 {
            get {
                return ResourceManager.GetString("长效稳定性", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面 的本地化字符串。
        /// </summary>
        internal static string 面 {
            get {
                return ResourceManager.GetString("面", resourceCulture);
            }
        }
    }
}
