//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTool.tc261 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTool.tc261.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 串口 的本地化字符串。
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optosky - TC261测试工具 的本地化字符串。
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休息时间 (ms) 的本地化字符串。
        /// </summary>
        internal static string 休息时间 {
            get {
                return ResourceManager.GetString("休息时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能 的本地化字符串。
        /// </summary>
        internal static string 功能 {
            get {
                return ResourceManager.GetString("功能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表 的本地化字符串。
        /// </summary>
        internal static string 图表 {
            get {
                return ResourceManager.GetString("图表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表线条累计超十条则重置 的本地化字符串。
        /// </summary>
        internal static string 图表线条累计超十条则重置 {
            get {
                return ResourceManager.GetString("图表线条累计超十条则重置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string 开始 {
            get {
                return ResourceManager.GetString("开始", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string 打开 {
            get {
                return ResourceManager.GetString("打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持久化测试 的本地化字符串。
        /// </summary>
        internal static string 持久化测试 {
            get {
                return ResourceManager.GetString("持久化测试", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string 日志 {
            get {
                return ResourceManager.GetString("日志", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次数 的本地化字符串。
        /// </summary>
        internal static string 次数 {
            get {
                return ResourceManager.GetString("次数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试已完成 的本地化字符串。
        /// </summary>
        internal static string 测试已完成 {
            get {
                return ResourceManager.GetString("测试已完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试已结束 的本地化字符串。
        /// </summary>
        internal static string 测试已结束 {
            get {
                return ResourceManager.GetString("测试已结束", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试异常 的本地化字符串。
        /// </summary>
        internal static string 测试异常 {
            get {
                return ResourceManager.GetString("测试异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束 的本地化字符串。
        /// </summary>
        internal static string 结束 {
            get {
                return ResourceManager.GetString("结束", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取温度 的本地化字符串。
        /// </summary>
        internal static string 获取温度 {
            get {
                return ResourceManager.GetString("获取温度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集 的本地化字符串。
        /// </summary>
        internal static string 采集 {
            get {
                return ResourceManager.GetString("采集", resourceCulture);
            }
        }
    }
}
